### ISSUE TITLE
希望能加入搜索关键词联想功能

### ISSUE THREAD

**Issue by lilynas** [f12998765/SpeedDial#2]
![tim 20180702000431](https://user-images.githubusercontent.com/31757534/42136318-8c0df69a-7d8b-11e8-8834-441aeadeb6c9.png)
这样应该会好用很多

**Comment by f12998765** [comment]
@KatLarry 这个新的样式用了一段时间，发现使用搜索框的次数少之又少，不如直接在地址栏中搜索来的方便，所以之后的更新准备去掉。如果你有兴趣，可以修改修改。
